// Generated by scripts/sync-listing-data.mjs from thalovant-languages v0.1.1.
// Source: https://github.com/thalovant/thalovant-languages/tree/512f1993bed2fe20b2f874da35b1ba4d95be893b
// Apache-2.0; see LICENSE-languages. Do not edit language rules here.
import type { ListingData } from './listing.js';
export const listingData: ListingData = {
  "sentence_ends": ".!?…;。！？；؟",
  "languages": {
    "az": {},
    "de": {},
    "en-US": {
      "trailing_words": [
        "in",
        "for",
        "at",
        "to",
        "on",
        "of",
        "with",
        "about",
        "from",
        "into",
        "the",
        "a",
        "an",
        "my",
        "is",
        "was"
      ],
      "question_openers": [
        "what",
        "when",
        "where",
        "who",
        "whom",
        "whose",
        "why",
        "how",
        "which",
        "is",
        "are",
        "am",
        "was",
        "were",
        "do",
        "does",
        "did",
        "can",
        "could",
        "will",
        "would",
        "should",
        "shall",
        "may",
        "might",
        "has",
        "have",
        "had"
      ],
      "written_forms": {
        "i": "I"
      },
      "slot_examples": {
        "incident": "the last one",
        "level": "fifty",
        "location": "Toronto",
        "query": "the garage door",
        "topic": "power"
      }
    },
    "es": {},
    "fr-FR": {
      "trailing_words": [
        "à",
        "a",
        "de",
        "du",
        "des",
        "au",
        "aux",
        "en",
        "dans",
        "pour",
        "sur",
        "avec",
        "chez",
        "vers",
        "par",
        "le",
        "la",
        "les",
        "un",
        "une",
        "mon",
        "ma",
        "mes"
      ],
      "question_openers": [
        "quel",
        "quelle",
        "quels",
        "quelles",
        "lequel",
        "laquelle",
        "que",
        "quoi",
        "qui",
        "quand",
        "où",
        "comment",
        "combien",
        "pourquoi"
      ],
      "question_words_anywhere": [
        "quel",
        "quelle",
        "quels",
        "quelles",
        "combien"
      ],
      "question_patterns": [
        "\\bqu'est[- ]ce\\b",
        "\\best[- ]ce\\b",
        "(?<!rendez)-(?:t-)?(?:il|elle|on|ils|elles|tu|je|vous|nous)\\b",
        "\\bt (?:il|elle|on)\\b",
        "\\bai je\\b"
      ],
      "slot_examples": {
        "incident": "le dernier",
        "level": "cinquante",
        "location": "Toronto",
        "query": "la porte du garage",
        "topic": "l'électricité"
      }
    },
    "it": {},
    "nl": {},
    "pt": {},
    "tr": {}
  }
};
